### ISSUE TITLE
AWS Terraform config doesn't work due to invalid aws_autoscaling_group argument

### ISSUE THREAD

**Issue by aknuds1** [coreos/tectonic-installer#571] opened 2017-05-06 04:29 UTC
The Terraform config for AWS doesn't work since an invalid [aws_autoscaling_group](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html) is in use: `tags`:

    terraform plan ../../platforms/aws
    2 error(s) occurred:

    * module.masters.aws_autoscaling_group.masters: : invalid or unknown key: tags
    * module.workers.aws_autoscaling_group.workers: : invalid or unknown key: tags

**Comment by s-urbaniak** [comment] 2017-05-08 08:28
Thanks for the report! Nevertheless, this is not a bug, but a feature ;-) We rely on a not-yet-merged AWS tagging feature, see [1] and include a custom AWS plugin in this repository.

Please follow the top-level README [2] to build an installer binary which includes the custom AWS plugin. More concretely it should be sufficient to invoke `make build` in the `installer` directory.

I am closing this issue then for now.

[1] https://github.com/hashicorp/terraform/pull/13574
[2] https://github.com/coreos/tectonic-installer/blob/master/README.md

**Closed by s-urbaniak** 2017-05-08 08:28 UTC

**Comment by aknuds1** [comment] 2017-05-08 21:02
@s-urbaniak I'm wondering if something changed, since the build fails differently from before: 

    $ PLATFORM=aws make plan
    Using build directory [/Users/arve/go/src/github.com/coreos/tectonic-installer/build/demo]
    sed "s|<PATH_TO_INSTALLER>|/Users/arve/go/src/github.com/coreos/tectonic-installer/installer/bin/darwin/installer|g" terraformrc.example > .terraformrc
    cd /Users/arve/go/src/github.com/coreos/tectonic-installer/build/demo && TERRAFORM_CONFIG=/Users/arve/go/src/github.com/coreos/tectonic-installer/.terraformrc terraform plan /Users/arve/go/src/github.com/coreos/tectonic-installer/platforms/aws
    Failed to load root config module: Error loading modules: module vpc: not found, may need to be downloaded using 'terraform get'
    make: *** [plan] Error 1

What do you think?

**Comment by aknuds1** [comment] 2017-05-08 21:25
@s-urbaniak I found out that the reason for the module error was that the directory build/<cluster>/.terraform already existed, which in turn means that make won't invoke `terraform get`. Might it be a good idea to always invoke `terraform get` to ensure that modules are up to date?

**Comment by aknuds1** [comment] 2017-05-08 21:34
@s-urbaniak I made a PR for always running `terraform get` instead of checking that the .terraform dir exists.
