### ISSUE TITLE
Leverage availability sets instead of vm scale sets

### ISSUE THREAD

**Issue by coresolve** [coreos/tectonic-installer#320] opened 2017-04-24 22:14 UTC
Avail sets leverage pvcs on a per instance basis. 

@jimzim for more detail here.

**Comment by jimzim** [comment] 2017-04-24 23:16
Currently Azure VMSS (VM ScaleSets) do not support adding disks to individual VMs at this time.  

In order to support PVCs, we will need to use VMs in Availability Sets for now.

**Comment by sozercan** [comment] 2017-04-24 23:16
#93

**Comment by s-urbaniak** [comment] 2017-04-25 07:54
This is a duplicate of #93, hence closing this. I suggest to continue the discussion in #93.

**Closed by s-urbaniak** 2017-04-25 07:54 UTC
Labels: kind/enhancement, kind/friction, platform/azure
