### ISSUE TITLE
Some resources are not cleaned up by `make destroy` or `terraform destroy`

### ISSUE THREAD

**Issue by yifan-gu** [coreos/tectonic-installer#329] opened 2017-04-25 01:41 UTC
**Issue**:
If a run `make apply`, `make destroy` and `make apply` with the same cluster-name, then the 2nd `make apply` will fail because `make destroy` doesn't clean up all the resources created by the 1st `make apply`.

The uncleaned resources are `s3 buckets`, `IAM roles`, `IAM instance profiles`, `loadbalancers`.

**To reproduce**:
Just run `make apply`, `make destroy` and `make apply`. Currently I don't have the error message in hand because I am hitting other errors (aws limit exceed)

My script for cleaning up the resources:
```
aws iam remove-role-from-instance-profile --instance-profile-name upgrade-test-master-profile --role-name upgrade-test-master-role
aws iam remove-role-from-instance-profile --instance-profile-name upgrade-test-worker-profile --role-name upgrade-test-worker-role

aws iam delete-role-policy --role-name upgrade-test-master-role --policy-name upgrade-test_master_policy
aws iam delete-role-policy --role-name upgrade-test-worker-role --policy-name upgrade-test_worker_policy

aws iam delete-role --role-name upgrade-test-master-role
aws iam delete-role --role-name upgrade-test-worker-role

aws iam delete-instance-profile --instance-profile-name upgrade-test-master-profile
aws iam delete-instance-profile --instance-profile-name upgrade-test-worker-profile

aws s3 rb s3://upgrade-test.us-west-2.staging.core-os.net --force  

aws elb delete-load-balancer --load-balancer-name upgrade-test-api-internal
aws elb delete-load-balancer --load-balancer-name upgrade-test-api-external
aws elb delete-load-balancer --load-balancer-name upgrade-test-console

```

Where my cluster is called `upgrade-test`.

**Comment by s-urbaniak** [comment] 2017-04-25 13:42
I am trying to reproduce this issue, but I can't. I see no leftover resources after a successful `make apply`, and `make destroy`, at least checking on instance profiles, elbs and s3 buckets.

May it be that the first `make apply` failed? In that mode, indeed resources must be cleaned up potentially manually, as the creation of them has not yet been committed to the state file.

**Comment by yifan-gu** [comment] 2017-04-25 18:50
@s-urbaniak Yeah, looks like this happens when the first `make apply` fails. However it is still inconvenient when `make apply` can fail for a lot of reasons, e.g. limit exceeded, resource already existed, etc.

**Comment by Quentin-M** [comment] 2017-04-25 20:56
Every resources created by `apply` should be present in the tfstate. If it is not the case as you seem to be hinting - but seems strange, then this is a critical TerraForm upstream bug and should be tracked there.

**Comment by alexsomesan** [comment] 2017-04-25 21:12
State updates are not atomic in Terraform.
If it hits the brakes hard because of an internal runtime error or process
abruptly terminated, some things might not make it into the statefile.

This used to be a lot worse half a year ago, so they are smoothing it out.

As a rule of thumb, don't abruptly terminate a running operation. Let it
error out and exit. Then apply again and it should pick up where it left
off. Or destroy and reapply from scratch.

**Comment by yifan-gu** [comment] 2017-04-26 01:51
OK, thanks for the help guys! Closing it for now as I think with the tfstate it should be solved.

**Closed** 2017-04-26 01:57 UTC
Labels: tectonic/terraform
