### ISSUE TITLE
Tectonic Console crashes after leaving idle

### ISSUE THREAD

**Issue by eddieesquivel** [coreos/tectonic-installer#1540] opened 2017-08-01 00:23 UTC
BUG

Tectonic version: tectonic-1.7.1-tectonic.1-rc.2
Platform: AWS

## What happened?

When leaving the console unattended for about 15 minutes the Tectonic console crashes with the following page on Chrome:

<img width="1432" alt="screen shot 2017-07-31 at 5 18 30 pm" src="https://user-images.githubusercontent.com/5018462/28803907-a8d80ccc-7614-11e7-8c79-5b109d5cecd0.png">

Clicking refresh on the page brings you back to the original page you were on (no need to log onto Tectonic again)

## What you expected to happen?

I expect Tectonic Contosle to be up and running

## How to reproduce it (as minimally and precisely as possible)?

Log onto Tectonic - go grab coffee at 111 Minna and come back.

**Comment by eddieesquivel** [comment] 2017-08-01 00:24
@Quentin-M

**Comment by ggreer** [comment] 2017-08-01 01:10
Any other info? I can't reproduce the memory leak on my own cluster.

**Comment by eddieesquivel** [comment] 2017-08-01 02:05
I'm running chrome on mac. Chrome version: 59.0.3071.115

Is there anything from Chrome side I can provide?

**Comment by eddieesquivel** [comment] 2017-08-01 02:23
screen shot 2017-07-31 at 7 16 16 pm
<img width="1438" alt="screen shot 2017-07-31 at 7 16 16 pm" src="https://user-images.githubusercontent.com/5018462/28806549-8d5df6bc-7625-11e7-8f35-2960779d3d57.png">

screen shot 2017-07-31 at 7 20 22 pm
<img width="1439" alt="screen shot 2017-07-31 at 7 20 22 pm" src="https://user-images.githubusercontent.com/5018462/28806566-a019515c-7625-11e7-9f47-66651f10bcd4.png">

Only 5 minutes apart.

@ggreer

**Comment by ggreer** [comment] 2017-08-01 03:11
There's definitely something to this, but I can't reproduce it on my own cluster. Very weird.

**Comment by ggreer** [comment] 2017-08-01 03:30
This was a bug in v1.8.0 of the console. It's fixed in v1.8.2. The PR that fixed it is https://github.com/coreos-inc/bridge/pull/1618

**Comment by Quentin-M** [comment] 2017-08-01 17:58
Thanks for the report and for digging the solution!

**Closed** 2017-08-01 17:58 UTC
