### ISSUE TITLE
no way to go back after clicking "manual boot"

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#1258] opened 2017-06-29 23:17 UTC
On the last screen of the installer. There is no way to return back to the previous page. The back button doesn't work. 

The only path left for the user is to download the progress file, click start over, then upload the progress file. 

There should be an option from the manual boot screen to abort and go back to the regular automatic boot.

**Comment by kyoto** [comment] 2017-07-26 00:44
Duplicate of #353

**Closed by kyoto** 2017-07-26 00:44 UTC
Labels: tectonic/frontend
