### ISSUE TITLE
tectonic-identity: pod pegs CPU cgroup and system is unreliable when using OIDC

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#801] opened 2017-05-20 20:08 UTC
**Problem:** The default CPU limits of tectonic-identity causes the Pod to peg the CPU. This in turn results in nearly unusable performance of kubectl and Tectonic Console. 

**Steps to Reproduce**: 

- Install Tectonic
- Download a kubeconfig that uses identity
- run `kubectl get pods -v=9`
- See `/identity` taking upwards of 400ms to respond

**Mitigation Steps**:

- `kubectl edit deployments -n tectonic-system tectonic-identity`
- Remove the cpu limits field
- CPU drops on the deployed pod to a normal level (below the original limit, confusingly)

*NOTE*: THIS IS NOT AN RCA. We should have a CPU limit on Dex but I don't know why this is happening.

**Comment by philips** [comment] 2017-05-20 20:08
cc @rithujohn191

**Comment by philips** [comment] 2017-05-20 20:09
@chancez didn't you have some Go runtime link related to this?

**Comment by chancez** [comment] 2017-05-20 22:59
I basically found that the CPU cgroups used by docker/kubernetes don't restrict the number of visible CPUs available to the Go runtime, so Go will set GOMAXPROCS to the number of cores on the host, despite the value of your cpu limit/request in the pod spec.

Additionally, I found the same results as you, that if you don't set any cgroup limits on Dex, it no longer consumes very much CPU at all. I also tried tweaking GOMAXPROCS to a value like 1, and setting CPU to `2`, but it seemed that Dex still ended up consuming all available CPU. All these observations were looking directly at Prometheus pod metrics. However, I'm not seeing anything like this in the rest of the Go programs running on these clusters, so I'm not so sure it's the runtime alone, but probably specific to how Dex runs ex: could be Dex causes the GC to run more, thus more effected by the cpu throttling as it falls behind.

**Comment by rithujohn191** [comment] 2017-05-22 17:59
Will try to reproduce and dig deeper.

**Comment by squat** [comment] 2017-05-22 22:38
I just ran some tests and I am seeing CPU usage pegged at 102m for console as well. This is not isolated to the dex pod. I ran this test:

1. Log into Tectonic Console
2. View Console pod CPU usage graphs
3. Verify Pods are using 102m
4. Edit tectonic-console deployment to remove pod resource limits and requests
5. View Console pod CPU usage graphs
6. Verify Pods are using 2m

**Comment by rithujohn191** [comment] 2017-05-22 22:45
I see the same thing with the tectonic-stats-emitter pod. Without resource limits defined in the deployment its at 4m for CPU usage, as soon as I put in the resource limits it spikes up to 104m when the limit is at 100m. So the trend seems to be that 100m (which is the resource limit) gets added to the usage in the graph

**Comment by rithujohn191** [comment] 2017-05-22 22:52
Tested it by setting resource limits to 50m for the stats emitter pod and now it shows that the CPU usage is 54m :(

**Comment by rithujohn191** [comment] 2017-05-23 16:36
Yesterday @kans and I tried to debug this. We realized that the graphs display the false values given to us by Prometheus. Which could mean they way we we have our queries set up are wrong. Will discuss further with the Prometheus for more insight.

**Comment by rithujohn191** [comment] 2017-05-23 18:47
After an offline discussion with @brancz, we concluded that what we have been reporting as CPU usage till now has actually been refering to the highest expected amount of resources the pod uses. Hence we observe the behavior detailed above every time we introduce CPU limits in the deployment.

What we need to do: We need to add a rule that accumulates the actual CPU usage and query that from console.

**Comment by chancez** [comment] 2017-05-23 18:49
I'm actually seeing it use the `request`, not the `limit`, but otherwise, yep.

**Comment by sym3tri** [comment] 2017-05-23 19:17
> See /identity taking upwards of 400ms to respond

@rithujohn191 but that still does not explain the above right?

If I understand correctly there are two issues:
1. Graphs in console have a bug
2. Dex becomes slow due to unknown reasons

Any progress on number 2?

**Comment by rithujohn191** [comment] 2017-05-23 20:16
Not yet need to analyze using pprof. Will update with findings.

**Comment by rithujohn191** [comment] 2017-05-23 20:33
There is no longer a good way to reproduce the issue of Dex becoming slow. I verified that adding CPU limits to the deployment does not slow down the response rate of Dex.

**Comment by robszumski** [comment] 2017-05-23 20:37
You can confirm that the graphs are wrong with:

```
$ kubectl top pods | grep identity
tectonic-identity-8985192-dsskr                   0m           6Mi
tectonic-identity-8985192-9hlqw                   0m           5Mi
```

**Comment by sym3tri** [comment] 2017-05-24 00:05
@philips were you seeing the slowness (not the CPU spikes) consistently?

**Comment by brancz** [comment] 2017-05-24 07:48
The cAdvisor metric we're currently querying is this metric:

https://github.com/google/cadvisor/blob/master/metrics/prometheus.go#L702-L703

I assumed that it was the limit because it uses the containers' limits (whatever that means for cAdvisor), so I can imagine that that is actually the requested resource in terms of Kubernetes. Some sample queries seem to confirm this.

As discussed with @rithujohn191 we'll add a recording rule to make sure we can quickly query this data for Pods, just like we did for the previously used metric, but will keep it around in case we want to display those values one day as well.

**Comment by brancz** [comment] 2017-05-24 12:38
Not that this solves the initial problem of Dex responding slowly, but https://github.com/coreos/tectonic-installer/pull/839 adds a recording rule to the Prometheus setup for the cpu usage in addition to its requests.

FWIW this returns results similar to what @robszumski commented as results coming from `kubectl top`.

Memory:

![screenshot from 2017-05-24 14-01-19](https://cloud.githubusercontent.com/assets/4546722/26403411/7221f12c-408e-11e7-96af-917a69afaf6f.png)

CPU:

![screenshot from 2017-05-24 14-00-58](https://cloud.githubusercontent.com/assets/4546722/26403419/7b33934c-408e-11e7-8bd7-91fbb9afcac6.png)

**Comment by rithujohn191** [comment] 2017-05-30 20:30
Closing out this issue since:
* CPU usage graph fixed in https://github.com/coreos/tectonic-installer/pull/868
* Cannot reproduce "dex being slow" issue.

**Closed by rithujohn191** 2017-05-30 20:30 UTC
Labels: priority/P1

**Comment by chancez** [comment] 2017-05-30 20:33
@rithujohn191 I still think the dex being slow issue might just be due to there only being a single instance of Dex. I do think it's worth bringing up running at least two Dex instances. Should I file a new issue? It's kinda odd we deploy 2 consoles but only 1 dex.

**Comment by rithujohn191** [comment] 2017-05-30 21:18
Already addressed in https://github.com/coreos/tectonic-installer/pull/856
