### ISSUE TITLE
Installer for AWS creates internal alias target for public facing record set for the API end point  

### ISSUE THREAD

**Issue by sir-rob** [coreos/tectonic-installer#1096] opened 2017-06-15 20:57 UTC
## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 1.6.4-tectonic.1
* Terraform version (`terraform version`): Terraform v0.9.4
* Platform (aws|azure|openstack|metal): AWS

## What happened?
During install I selected the option "Do not create a private zone." which seems to create a faulty record set for the public facing api end point. The api end point is pointing to the internal ELB.

This causes kubectl command to fail, as they are routing to the internal IP, which is not accessible outside of the cluster.

To work around the issue I was able to manually edit the the route53 record set and change the alias to the public facing elb.

## What you expected to happen?
The installer sets up the correct external facing record set for the api and kubectl commands work outside of the cluster.

## How to reproduce it (as minimally and precisely as possible)?
Install a new cluster on AWS using the GUI based installer. On the networking page, under the DNS section, select the option "Do not create a private zone".

**Comment by sir-rob** [comment] 2017-06-15 20:57
@robszumski

**Comment by coresolve** [comment] 2017-06-16 00:34
verified reproducable.
example tfvars file: 
[terraform.tfvars.txt](https://github.com/coreos/tectonic-installer/files/1079401/terraform.tfvars.txt)

**Comment by s-urbaniak** [comment] 2017-06-28 15:00
I was assuming that I need to fix some A-record creation in our terraform templates, but after discussing with @alexsomesan I believe we have some basic misconception in the frontend.

If you specify "Do not create a private zone." in the frontend and specify a bring-your-own zone, our templates internally still assume the invariant that the bring-your-own zone is also a private one. Hence it will create A-records for the internal ELBs in it.

Question from my side: Is the external zone ID a private or public one?

If it is a private one, I cannot really spot a bug in the templates. If it is a public one, then we currently don't support the possibility to host everything in the public zone only. Currently we always create internal ELBs with a self-provisioned internal zone or an external bring-your-own private zone. The variable name `tectonic_aws_external_private_zone` and its description try to make this clear:

```
variable "tectonic_aws_external_private_zone" {
  default = ""

  description = <<EOF
(optional) If set, the given Route53 zone ID will be used as the internal (private) zone.
This zone will be used to create etcd DNS records as well as internal API and internal Ingress records.
If set, no additional private zone will be created.

Example: `"Z1ILINNUJGTAO1"`
EOF
}
```

Maybe we can simply make it in the frontend more explicit that the external zone must be a private one?

**Comment by robszumski** [comment] 2017-06-29 00:29
Thoughts @sir-rob and @coresolve?

**Comment by coresolve** [comment] 2017-06-30 17:36
it would make send to fit make the external zone the private one in this case.

**Comment by sym3tri** [comment] 2017-07-01 00:07
I realize this is not what we have today, but the desired behavior here is that users have 2 options regarding DNS when installing Tectonic on AWS:

1. (default) We create a new internal hosted zone matching the selected public hosted zone and put all our A records etc there (this works today).
2. If the user opts to, we omit creating the internal zone and instead put all records into the public hosted zone. This option is less ideal for reliability and security reasons, but for some users is the only option. This is the way the original version of the Tectonic AWS installer worked. We've gotten numerous feedback from customers and this is a common enough use-case that we need to enable this path (need to build support for this on the backend, i.e. make what was in the UI work).

**Comment by edevenport** [comment] 2017-08-23 09:26
@squat @sym3tri - I have been investigating this issue and have been trying to determine how we can accommodate option 2. If `tectonic_aws_external_private_zone` is set to match the public zone_id, currently both the public and private records are assigned to the public domain. However, we lose the external API record since the public and private host record names are the same. Only a single `[cluster_name]-api` is created and it points to the internal ELB.

If we want to preserve both the internal and external API host records on a single public domain, then they cannot have the same name. There are three options I have been exploring:

1. Rename the public API host record: `[cluster-name]-api-ext.example.com`
2. Rename the private API host record: `[cluster-name]-api-int.example.com`
3. Assign the internal host records to a subdomain: `[cluster-name]-api.internal.example.com`

I have been doing some experimentation with option 3 and it seems possible with minimal changes, but further testing is required. The logic is that if `internal_zone_id == external_zone_id`, assign the internal records to a `[record_name].internal` subdomain. If the internal and external zone_id do not match, then we can treat them separately and assign the records as they are now.

Thoughts or concerns on this approach?

**Comment by edevenport** [comment] 2017-08-23 21:48
@squat I'm not sure if this helps, but I was testing the subdomain assignment for the internal route53 records in `modules/aws/master-asg/elb.tf`.

Within the `api_internal` resource, for example:

    name    = "${var.custom_dns_name == "" ? var.cluster_name : var.custom_dns_name}-api.${var.internal_zone_id == var.external_zone_id ? format("internal.%s", var.base_domain) : var.base_domain}"`

**Comment by sym3tri** [comment] 2017-08-30 08:19
@sir-rob @coresolve @robszumski This should be fixed now that https://github.com/coreos/tectonic-installer/pull/1751 has merged. If you're feeling ambitious you can try a custom build from master to see if it works for you.

**Closed by sym3tri** 2017-08-30 08:19 UTC
Labels: kind/bug, platform/aws, priority/P1, size/L
