### ISSUE TITLE
Support for Weave Net?

### ISSUE THREAD

**Issue by trescst** [coreos/tectonic-installer#1368] opened 2017-07-12 15:18 UTC
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST/QUESTION

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 1.6.7
* Terraform version (`terraform version`): 0.9.6
* Platform (aws|azure|openstack|metal): AWS

## What happened?

I am looking into the possibility of replacing Flannel with Weave Net.  I assumed it would be fairly straight forward, but I am running into some issues...

I made the following changes:
* edited the security groups (Weave Net uses ports 6783 & 6784)
* in `modules/bootkube/resources/manifests/` I replaced the kube-flannel.yml (DaemonSet) with [kube-weave.yml](https://gist.github.com/trescst/6cfc958eeeaf0311cd8c4609bb546d51)
* some minor changes in kubelet.service (for example: that /etc/cni/net.d/ is used instead of /etc/kubernetes/cni/net.d/)

At first everything seemed to be working (`kubectl get nodes` showed that all nodes were "Ready"), unfortunately all of the api, controller and dns pods remain in the "ContainerCreating" state...

When describing one of those pods in "ContainerCreating" state I get:
```
  48m	1s	2086	kubelet, ip-10-0-38-214.us-east-2.compute.internal		Warning	FailedSync	Error syncing pod, skipping: failed to "CreatePodSandbox" for "kube-controller-manager-3857991999-llxmh_kube-system(077bb534-670e-11e7-98e9-0295e4ade107)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-controller-manager-3857991999-llxmh_kube-system(077bb534-670e-11e7-98e9-0295e4ade107)\" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod \"kube-controller-manager-3857991999-llxmh_kube-system\" network: open /run/flannel/subnet.env: no such file or directory"
```

Although I have not installed/configured flannel it show up in the logs...  Anybody an idea what I am missing?  Or what I can try?  I want to do all legwork to get this implemented, just needs a gentle push into the right direction.

**Comment by SEJeff** [comment] 2017-07-12 19:26
Dupe of #187

**Comment by sym3tri** [comment] 2017-07-13 00:30
Thanks for the request. Closing b/c duplicate. 

We may look into supporting other CNI implementations in the future, but that is not currently supported.

**Closed by sym3tri** 2017-07-13 00:30 UTC
