### ISSUE TITLE
Implement Conformance Test Grid

### ISSUE THREAD

**Issue by Quentin-M** [coreos/tectonic-installer#1119] opened 2017-06-19 16:06 UTC
@ethernetdan suggested we start using upstream's [bootstrap.py](https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap.py) and [kubetest](https://github.com/kubernetes/test-infra/tree/master/kubetest) in order to implement a test grid for conformance tests.

He notes that one issue is that we would probably have to modify kubetest for our purpose, and that these two project often changes / break. Forking them is also an issue because it introduces drift over time.

Therefore this project would require quite a bit of design work and implementation work too.
This is pretty related to https://github.com/coreos/tectonic-installer/issues/1099, which is about exposing a dashboard for our smoke tests, etc.

**Comment by rithujohn191** [comment] 2017-07-10 20:56
Needs more investigation.

**Comment by mxinden** [comment] 2017-07-20 12:13
Short update: I am currently working on #1445 replacing our bash scripts with RSpec. In the long run I would like to have the conformance tests included in this as well. That being said I think it makes sense to use the same dashboard for both the conformance and smoke tests. This would make this issue a duplicate of #1099. If you, @Quentin-M & @rithujohn191, don't mind, I would like to close this issue in favour of #1099. What do you think?

**Comment by squat** [comment] 2017-07-20 17:10
SGTM @mxinden

**Comment by Quentin-M** [comment] 2017-07-20 18:34
Conformance tests will be executed, against various configuration of images, every few hours, by the release automation jobs. There will therefore be a separation of concern between the Smoke Tests (PRs, maintained by the Tectonic Installer team, and the Conformance Tests (Periodically, on various release-like tarballs, maintained by the Release Automation team). Therefore they probably will be different dashboards.

**Closed** 2017-09-05 15:48 UTC
Labels: area/testing, migrate-issue
