### ISSUE TITLE
Fix flaky AWS test

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#818] opened 2017-05-23 16:53 UTC
We are randomly getting timeouts on tests with output like:

```
* aws_instance.etcd_node.0: Error launching source instance: timeout while waiting for state to become 'success' (timeout: 15s)
```

For a real example see:
https://github.com/coreos/tectonic-installer/pull/805#issuecomment-303185634

**Comment by Quentin-M** [comment] 2017-05-23 17:51
I'd start by verifying what went in the new Terraform build we are using. Timeout 15s seems weird...

**Comment by kans** [comment] 2017-05-24 02:03
Adding TF_LOG=TRACE to terraform apply indicates that these timeouts are actually caused by poorly handled AWS API rate limiting.  Refreshing jenkins results in the tests ... testing stuff (when we don't hit the limits).  Rate limiting is account wide, though specific to a given region.  Quentin filed a ticket to increase the limits.  We should distribute smoke tests across regions to actually fix the problem.  I started on the fix, but didn't get to far - if someone whats to take up the mantle, thats fine with me.

**Comment by s-urbaniak** [comment] 2017-05-24 05:12
I'll open an issue and work on spreading smoke tests across regions.

**Comment by squat** [comment] 2017-05-24 21:38
We merged @s-urbaniak's PR so we should now wait and check if we continue to experience test flakiness. Hopefully this solves the issue. We should close this and re-open if we continue to experience flakiness.

**Comment by kans** [comment] 2017-05-24 21:41
Yeah, closing for now.

**Closed by kans** 2017-05-24 21:41 UTC
Labels: area/testing, kind/bug, priority/P0, tectonic/terraform
